[package]
name = "we-bt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.3"
itertools = "0.10.5"
rand = "0.8.5"
strum = {version="0.24.1", features=["derive"]}
